---
soap:
    publishTo:  'https://localhost:9050/OSCARS/PSSService'

circuitService:
    id:                 'sdn'
    sdn:               true
    logRequest:         true
    logResponse:        true

definitions:
    models:             'defs-models.yaml'
    services:           'defs-services.yaml'

# generic impl / params config from here on
verify:
    impl:               'net.es.oscars.pss.sdn.SdnVerifier'
    params:

notify:
    impl:               'net.es.oscars.pss.sdn.SdnNotifier'

connectorDirectory:
    impl:               'net.es.oscars.pss.sdn.SdnConnectorDirectory'

deviceConnectorMap:
    impl:               'net.es.oscars.pss.sdn.SdnDeviceConnectorMap'

deviceModelMap:
    impl:               'net.es.oscars.pss.sdn.SdnDeviceModelMap'

deviceResolve:            
    impl:               'net.es.oscars.pss.sdn.SdnDeviceAddressResolver'

workflow:
    impl:               'net.es.oscars.pss.workflow.FifoWF'

validate:
    impl:               'net.es.oscars.pss.sdn.SdnValidator'

