---
- id: "juniper-mx"
  services: 
    - id:               eompls
      configGenerator:  "net.es.oscars.pss.eompls.junos.MXConfigGen"
    
    - id:               sdn
      "configGenerator: "net.es.oscars.pss.sdn.SdnConfigGen"
            
